#!/bin/bash

if [ ! -f "get-cp-vars" ]; then
  echo "get-cp-vars not found. Please cd to scripts directory."
  exit 1
fi

source get-cp-vars

mkdir -p  $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default

rsync -av $SRC/knowledge/modules/geonames_index  $DEST/library/knowledge/modules

cp $SRC/knowledge/modules/openstreetmap/DIGEST $DEST/library/knowledge/modules/openstreetmap
cp $SRC/knowledge/modules/openstreetmap/INFO.json $DEST/library/knowledge/modules/openstreetmap
cp $SRC/knowledge/modules/openstreetmap/MANIFEST $DEST/library/knowledge/modules/openstreetmap

rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/0 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/1 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/2 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/3 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/4 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/5 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/6 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/7 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/8 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/9 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/10 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/11 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default
rsync -av $SRC/knowledge/modules/openstreetmap/mod_tile64/default/12 $DEST/library/knowledge/modules/openstreetmap/mod_tile64/default

IIAB=/usr/lib/python2.7/site-packages/iiab
cp ../osm-fixes/etc.iiab.conf $DEST/etc/iiab.conf
cp -f ../osm-fixes/map_search.py $IIAB
cp -f ../osm-fixes/map.html $IIAB/static/
cp -f ../osm-fixes/l.control.geosearch.js $IIAB/static/lib/leaflet/geosearch/
