#!/bin/bash

if [ ! -f "get-cp-vars" ]; then
  echo "get-cp-vars not found. Please cd to scripts directory."
  exit 1
fi

source get-cp-vars

mkdir -p $DEST/library/rachel/www/modules
#ln -s $DEST/library/rachel/www $DEST/var/www/html/rachel

rsync -av $SRC/rachel/modules/ck12  $DEST/library/rachel/www/modules
rsync -av $SRC/rachel/modules/ebooks-en  $DEST/library/rachel/www/modules
rsync -av $SRC/rachel/modules/hesperian_health  $DEST/library/rachel/www/modules
rsync -av $SRC/rachel/modules/infonet  $DEST/library/rachel/www/modules
rsync -av $SRC/rachel/modules/medline_plus  $DEST/library/rachel/www/modules
rsync -av $SRC/rachel/modules/olpc  $DEST/library/rachel/www/modules
rsync -av $SRC/rachel/modules/practical_action  $DEST/library/rachel/www/modules
rsync -av $SRC/rachel/modules/phet-html  $DEST/library/rachel/www/modules
rsync -av $SRC/rachel/modules/powertyping  $DEST/library/rachel/www/modules
rsync -av $SRC/rachel/modules/radiolab  $DEST/library/rachel/www/modules
rsync -av $SRC/rachel/modules/scratch  $DEST/library/rachel/www/modules
