#!/bin/bash 
for f in `ls `; do
  if [ -f $f ]; then
   dummy=
   #sed  -i -E  's%<link rel="stylesheet" href=http://wikem/org/w/load.*/>%<link rel="stylesheet" href="../w/wikem.css" />%g'  $f 
  else
     # must be a directory
     for child in `ls $f`; do
        if [ -f $f/$child ]; then
            echo "child $child"
#            sed  -i -E  's%<link rel="stylesheet" href=http://wikem/org/w/load.*/>%<link rel="stylesheet" href="../../w/wikem.css" />%g'  $f/$child
        else
            #must be a directory holding grandchildren at level 2
            for grandchild in `ls $f/$child`; do
               if [ -f $f/$child/$grandchild ]; then
                   echo "grandchild $f/$child/$grandchild"
#                  sed  -i -E  's%<link rel="stylesheet" href=http://wikem/org/w/load.*/>%<link rel="stylesheet" href="../../../w/wikem.css" />%g'  $f/$child/$grandchild 
               fi
            done

        fi
     done
  fi
done
