#!/bin/bash -x
# first modify the links in SRC_LINKS_DIR, then cp the httrack files into docs,images,videos 

# define the settings
PREFIX=/var/www/html/modules
SRC_LINKS_DIR=$PREFIX/en-wikem
TARGET_DATA_DIR=$PREFIX/en-wikem-george # originally a httrack output
OUTPUT_DIR=$TARGET_DATA_DIR/output

# make all the output directories
mkdir -p ${OUTPUT_DIR}/docs
mkdir -p ${OUTPUT_DIR}/images
mkdir -p ${OUTPUT_DIR}/videos
mkdir -p ${OUTPUT_DIR}/duplicates
mkdir -p ${OUTPUT_DIR}/errors
mkdir -p ${OUTPUT_DIR}/wiki
mkdir -p ${OUTPUT_DIR}/w
cp ./wikem.css ${OUTPUT_DIR}/w 

# change the link in the source directory
pushd ${SRC_LINKS_DIR}/
# first make all the references at the first level in wiki `to http://wikem/w relative
for f in `ls wiki/`; do
  if [ -f wiki/$f ]; then
   sed   -E  's%<link rel="stylesheet" href="\.\./w/load.*/>%<link rel="stylesheet" href="../w/wikem.css" />%g'  wiki/$f > ${OUTPUT_DIR}/wiki/$f
  fi
done

#      sed  -i -E  's%https*://([-._/a-z0-9A-Z]*/)*([-_/a-z0-9A-Z]*\.(png|jpg|jpeg)+)+%../images/\2%g' copy 
#   sed   -E  's%https*://([-._/a-z0-9A-Z]*/)*([-_/a-z0-9A-Z]*\.(png|jpg|jpeg)+)+%../images/\2%g' $1 
