#!/bin/bash

source ../find-source

CP_ZIM=../../content/kiwix/cp-zim

$CP_ZIM wikipedia_es_all
$CP_ZIM wiktionary_es_all
$CP_ZIM wikibooks_es_all
$CP_ZIM wikisource_es_all
$CP_ZIM wikiversity_es_all
$CP_ZIM wikivoyage_es_all
$CP_ZIM wikipedia_en_for_schools_opt

xsce-make-kiwix-lib
