#!/bin/bash
# mk-other-kalite
#
# create a parallel install of kalite for a specific language
# directory should be /library/ka-lite-xx where xx is language code
# port is expected to be 8007 for ES and 8006 for FR.
# In case of (air)PORT gate changes, check the overhead screens:
# https://github.com/iiab/iiab/wiki/IIAB-Networking#list-of-ports--services

echo -e '\nSee "KA Lite Administration: What tips & tricks exist?"'
echo -e 'at http://FAQ.IIAB.IO\n'

if [ "$#" -lt 2 ]; then
    echo "usage: $0 <lang code, e.g. es> <new kalite port, e.g. 8007> <optional path to both language packs>"
    exit 1
fi

# accommodate venv
KA=/usr/local/kalite/venv/bin/kalite

KALITE_HOME=/library/ka-lite-$1
mkdir -p $KALITE_HOME
export KALITE_HOME=$KALITE_HOME

$KA manage setup --username=Admin --password=changeme --noinput

# register
$KA manage generate_zone

# get kalite English language pack - takes awhile and seems to re-download if run again

if [ -z "$3" ]; then
    $KA manage retrievecontentpack download en
else
    $KA manage retrievecontentpack local en $3/en.zip
fi

# get new lang pack

if [ -z "$3" ]; then
    $KA manage retrievecontentpack download $1
else
    $KA manage retrievecontentpack local $1 $3/$1.zip
fi

# try to hack up a service file
cd /etc/systemd/system
cp kalite-serve.service kalite-$1-serve.service

sed  -i -e  "s%KALITE_HOME=/library/ka-lite%KALITE_HOME=$KALITE_HOME%g" kalite-$1-serve.service
sed  -i -e  "s%--port=8008%--port=$2%g" kalite-$1-serve.service

systemctl start kalite-$1-serve.service
systemctl enable kalite-$1-serve.service

echo -e "\nREMEMBER TO OPEN PORT(S) in iiab-gen-iptables !\n"
