#!/bin/bash
# script to convert downloaded videos from list of youtube_ids to smaller files
# reads and writes to videos directory below current directory

disable=
case $# in
0)
   echo "\nPass the list name, and any non_blank to test,but not copy"
   exit 1
   ;;
2)
   disable="1"
   ;;
esac

if [ ! -f $1 ];then
    echo Could not find $1. Quitting.
    exit 1
fi

# rm -f youtube-dl.log
for f in `cat $1`; do
   echo $f
   if [ -z "$disable" ];then
      ./mk-vid-sm $f
   fi
done
