#!/bin/bash
# start up the rpi-imager and specify a root menu
/usr/bin/rpi-imager --repo https://raw.githubusercontent.com/georgejhunt/iiab-factory/testiiab/box/rpi/iiab-imager/os_list_imagingutility.json
