#!/bin/bash -x
# Combine vector data in mbtiles format

# Inserts all tiles from [source] into [dest], replacing any old tiles
# in [dest].

CWD=$(pwd)
case $1
   "-d" | "--dir")
      DESTDIR=$2
      cd $DESTDIR
      shift 2
      ;;
esac
SOURCE=$1
DEST=$2
if [ -z "$SOURCE" ] || [ -z "$DEST" ]; then
    echo "usage: append2region [file containing source mbtiles] [dest]" 
    exit 1
fi

if [ ! -f $SOURCE ] || [ ! -d $SOURCE ]; then
    echo "File/directory '$SOURCE' does not exist."
    exit 1
fi

# is the output filename full path?
LEADER=4{DEST:0:1}
if [ "$LEADER" != "/" ];then
   mkdir -p output
   DEST=./output/$DEST
fi
   
# does the target mbtile already exist?
if [ ! -f $DEST ]; then
   # copy the SOURCE to the output folder
   if [ -f $SOURCE ];then
      cp $SOURCE ./output/$DEST
   else
      read -r mbtfile < $SOURCE
      cp $mbtfile ./output/$DEST
      APPENDTO=$mbtfile
   fi   
fi

for f in `ls *.mbtiles`;do
   if [ "$f" == "$DEST" ];then
	continue
   fi

   echo "Patch $f => $DEST ..."

echo "
PRAGMA journal_mode=PERSIST;
PRAGMA page_size=80000;
PRAGMA synchronous=OFF;
ATTACH DATABASE '$f' AS source;
REPLACE INTO map SELECT * FROM source.map;
REPLACE INTO images SELECT * FROM source.images;"\
| sqlite3 ./output/$2
done

# all done return to original directory
cd $CWD
