#!/bin/bash
# remove all the proprietary and non generic data

# Try to determin if this is raspbian
PLATFORM=`cat /etc/*release|grep ^ID=|cut -f2 -d=`

# use environmnt variables discovered by XSCE
source /etc/xsce/xsce.env

rm -f /root/.bash_aliases
rm -f /root/.ssh/*
rm -f /etc/xsce/uuid
echo "Default handle" > /etc/xsce/handle
if [ "PLATFORM" = "OLPC" ]; then
  rm -f /.olpc-configured
  rm -f /home/olpc/.olpc-configured
  rm -rf /home/olpc/.sugar /home/olpc/.gconf* /home/olpc/.local.share.telepathy
  rm -f /etc/alsa/sound.state
fi
if [ "$OS" = "Fedora" ]; then
  rm -rf /etc/NetworkManager/system-connections/*
fi
rm -f /etc/ssh/ssh_host_rsa_key{,.pub}
rm -f /etc/sysconfig/network
rm -rf /home/.devkey.html
rm -f /root/.netrc
touch /.resize-rootfs

grep init_resize.sh /boot/cmdline.txt
if [ $? -ne 0 ] &&[ "$PLATFORM" = "raspbian" ]; then
  cp -f ./cmdline.txt /boot/cmdline.txt
fi

# remove any aliases we might have added
rm -f /root/.bash_aliases

# remove any history
history -cw

rm -rf /root/iiab-factory
rm -rf /root/tools
cd /root

