#!/bin/bash

IMG=iiab-6.4-180207-medbox-beta2.1-content-ready-g3ea4256.img

echo $IMG

ZIPMD5=`cat $IMG.zip.md5.txt |cut  --delimiter=' ' --fields=1`

ia upload $IMG $IMG.zip --metadata="mediatype:software" --metadata="collection:internetinabox" \
 --metadata="title:Medical Internet in a Box Beta 2.1 Content Ready" \
 --metadata="language:eng" \
 --metadata="description:Medical Internet in a Box Beta for Raspberry Pi<BR>Contains no Content<BR>Release: $IMG" \
 --metadata="creator:Internet in a Box" \
 --metadata="subject:rpi"  \
 --metadata="subject:wikipedia" \
 --metadata="subject:medical" \
 --metadata="licenseurl:http://creativecommons.org/licenses/by-sa/4.0/" \
 --metadata="zip_md5:$ZIPMD5"
