#!/bin/bash -x
# resize the SD card to minimum size and zip it to image directory
# assume /dev/sdg2 is partition to be shrunk
# parameter 1 - output file name
# parameter 2 - optional root device partition otherwise /dev/sdg2
# parameter 3 - optional image directory otherwise CWD
# Automatically determine a size for the output disk image
# (including root, swap, and boot partitions).
#
# This is calculated by using resize2fs to shrink, then adding the space
# occupied by previous partitions
# Assumes root is last partition

if [ $# -eq 0 ]; then
   echo "Usage: $0 filename (no .img), optional rootfs device (like /dev/sdg3), optional image directory (like /curation/images), otherwise CWD"
   exit 1
fi

# get the current settings
source factory-settings

FILENAME=$1.img

if [ -z $2 ]; then
   PARTITION=/dev/sdg2
else
   PARTITION=$2
fi

if [ ! -b $PARTITION ];then
   echo "Device $PARTITION not found".
   exit 1
fi

if [ -z $3 ]; then
   IMAGE_DIR=$PWD
else
   IMAGE_DIR=$3
fi

mkdir -p $IMAGE_DIR
cd $IMAGE_DIR
mkdir -p /mnt/sdcard

umount $PARTITION
umount /media/usb*

# setup to expand on boot
# assume expand service is installed

mount $PARTITION /mnt/sdcard

if [ ! -d /mnt/sdcard/opt/iiab/iiab ]; then
  echo "Device is not IIAB root partition. Exiting."
  exit 1
fi

touch /mnt/sdcard/.resize-rootfs

# create id for image
pushd /mnt/sdcard/opt/iiab/iiab
HASH=`git log --pretty=format:'g%h' -n 1`
YMD=$(date +%y%m%d)
FILENAME=$(printf "%s-%s-%s-%s-%s.img" $PRODUCT $VERSION $YMD $1 $HASH)
echo $FILENAME > /mnt/sdcard/.iiab-image
git branch >> /mnt/sdcard/.iiab-image
git log -n 5 >> /mnt/sdcard/.iiab-image
cat /mnt/sdcard/etc/rpi-issue >> /mnt/sdcard/.iiab-image

popd

# clean up some files from development
rm -f /mnt/sdcard/library/awstats/*
rm -f /mnt/sdcard/var/log/apache2/*
rm -f /mnt/sdcard/var/log/nginx/*
rm -f /mnt/sdcard/etc/iiab/uuid
rm -f /mnt/sdcard/library/www/html/local_content/USB*
rm -f /mnt/sdcard/usb*

# sanitize wpa_supplicant.conf but preserve country code
COUNTRY_CODE_LINE=`cat /mnt/sdcard/etc/wpa_supplicant/wpa_supplicant.conf | grep  country=`
cat <<EOF > /mnt/sdcard/etc/wpa_supplicant/wpa_supplicant.conf
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
EOF
echo $COUNTRY_CODE_LINE >> /mnt/sdcard/etc/wpa_supplicant/wpa_supplicant.conf

echo $FILENAME > /mnt/sdcard/etc/iiab/openvpn_handle
truncate --size 0 /mnt/sdcard/opt/admin/cmdsrv/cmdsrv.0.2.db

umount /mnt/sdcard

# now resize

DEVICE=${PARTITION:0:-1}
PART_DIGIT=${PARTITION: (-1)}

PART_START_SECTOR=`parted -sm  $DEVICE unit s print|cut -d: -f1,2|grep $PART_DIGIT:|cut -d: -f2`
root_start=${PART_START_SECTOR:0:-1}

# total prior sectors is 1 less than start of this one
prior_sectors=$(( root_start - 1 ))

# resize root file system
umount $PARTITION
e2fsck -fy $PARTITION
minsize=`resize2fs -P $PARTITION | cut -d" " -f7`
block4k=$(( minsize + 100000 )) # add 400MB OS claims 5% by default
resize2fs $PARTITION $block4k

umount $PARTITION
e2fsck -fy $PARTITION

# fetch the new size of ROOT PARTITION
blocks4k=`e2fsck -n $PARTITION 2>/dev/null|grep blocks|cut -f5 -d" "|cut -d/ -f2`

root_end=$(( (blocks4k * 8) + prior_sectors ))

umount $PARTITION
e2fsck -fy $PARTITION

umount $PARTITION

# resize root partition
parted -s $DEVICE rm $PART_DIGIT
parted -s $DEVICE unit s mkpart primary ext4 $root_start $root_end

umount $PARTITION

# set the percentage reserved by OS to 1 percent
tune2fs -m 1 $PARTITION

# try to repair any errors
e2fsck -fy $PARTITION

# set the percentage reserved by OS to 1 percent
#tune2fs -m 1 $PARTITION


# recalc last sector and read that many sectors from card
last_sector=`parted -s $DEVICE unit s print |tail -2 |head -1| awk '{print $3}'`
last=${last_sector:0:-1}
echo "last sector: $last"
