#!/bin/bash
# copy image to SD card
# assume /dev/sdc is card
# parameter 1 - image file name
# parameter 2 - optional root device partition otherwise /dev/sdb

if [ $# -eq 0 ]; then
   echo "Usage: $0 filename (with .img), optional output device (like /dev/sdb)"
   exit 1
fi

IMG=$1

if [ ! -f $1 ]; then
  echo "Image $1 not found."
  exit 1
fi

if [ -z $2 ]; then
   SDCARD=/dev/sdb
else
   SDCARD=$2
fi

RESIZE=0
mkdir -p /mnt/sdcard

BOOTPART=$SDCARD"1"
FSPART=$SDCARD"2"
echo "boot part is $BOOTPART fs part is $FSPART"

df
echo "WARNING writing to $SDCARD"
echo "Are you sure? "
read -p "Press y to continue or any other key to stop. " -n 1 -r
echo    # (optional) move to a new line

if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Writing to $SDCARD"
    umount $BOOTPART $FSPART
    dd if=$IMG of=$SDCARD bs=4M status=progress

    sleep 5 # wait for card to be read
    partprobe $SDCARD

    umount $BOOTPART $FSPART
    mount  $FSPART /mnt/sdcard
    if [ -f /mnt/sdcard/.resize-rootfs ]; then
        RESIZE=1
        rm /mnt/sdcard/.resize-rootfs
    fi
    umount /mnt/sdcard

    if [ $RESIZE -eq "1" ]; then
        echo "Resizing $SDCARD"
        umount $BOOTPART $FSPART

        growpart $SDCARD 2
        sleep 5 # wait for card to be read
        partprobe $SDCARD

        umount $BOOTPART $FSPART
        e2fsck -f $FSPART
        resize2fs $FSPART
    fi
    umount $BOOTPART $FSPART
    df
fi
