#!/bin/bash -x

# Rebuilds local library.xml in case ZIM files added to /library/zims/content
iiab-make-kiwix-lib

# /usr/bin/kalite venv wrapper does this: export KALITE_HOME=/library/ka-lite
kalite manage generate_zone || true    # Overrides "set -e" allowing repeat run
# Register with KA Lite - just the anonymous registration

# WARNING: /tmp/en.zip (and all stuff in /tmp) is auto-deleted during reboots
cd /tmp/    # Or /opt/iiab/downloads or /library/downloads if you prefer
if [ -f en.zip ]; then
    if [ $(wc -c < en.zip) -ne 929916955 ]; then
        echo -e "\nERROR: /tmp/en.zip must be 929,916,955 bytes to proceed.\n" >&2
        exit 1
    else
	echo -e "\nUsing existing /tmp/en.zip whose 929,916,955 byte size is correct!\n"
    fi
else
    wget http://pantry.learningequality.org/downloads/ka-lite/0.17/content/contentpacks/en.zip
fi
kalite manage retrievecontentpack local en en.zip
# NEW WAY ABOVE - since 2018-07-03 - installs KA Lite's mandatory English Pack
# kalite manage retrievecontentpack download en
# OLD WAY ABOVE - fails w/ sev ISPs per https://github.com/iiab/iiab/issues/871
