#!/bin/bash -x
set -e

IPATH=/opt/iiab/iiab-factory/box/rpi/imager/docs

if [ $# -gt 0 ]; then
   pandoc -s $IPATH/$1.md -o $IPATH/$1.html
else
   pandoc -s $IPATH/README.md -o $IPATH/README.html
   pandoc -s $IPATH/GET-STARTED-GUIDE.md -o $IPATH/GET-STARTED-GUIDE.html
fi

# 2018-09-08: both README.html and GET-STARTED-GUIDE.html will be published to:
# http://download.iiab.io/packages/imager/
