#!/bin/bash -x
# Create a USB stick to double boot UEFI/mbr in 32bit (maybe 64bit) tiny core linux
# For the purpose of duplicating rpi SD cards on a windows laptop

#Copyright George Hunt @ georgejhunt@gmail.com
# attributioon James Camron http://dev.laptop.org/git/users/quozl/mktinycorexo/

PERSIST=/opt/cache/tce
ARCH=x86
CORE_VERSION=9.x
URL=http://download.iiab.io/packages/imager
mkdir -p $PERSIST
if [ $(id -u) = "0" ]; then
   echo This script should be run as user tc
   exit 1
fi

tce-load -wi dosfstools e2fsprogs
dev=sdb
efi=${dev}2
ext=${dev}3
sudo umount /mnt/$efi
sudo umount /mnt/$ext
sudo umount /dev/$efi
sudo umount /dev/$ext

function p_begin {
    if [ "$COLOUR" = "yes" ]; then
        echo -ne "\e[1;96m$1\e[0;39m"
    else
        echo -n "$1"
    fi
}

function p_end {
    if [ "$COLOUR" = "yes" ]; then
        echo -e "\e[1;92m$1\e[0;39m"
    else
        echo "$1"
    fi
}

sudo fdisk /dev/${dev} << EOF
d

d

d

d


n
p
1
2048
+1M
n
p
2

+10M
n
p
3

+70M
t
1
4
t
2
1
t
3
83
w
EOF

sleep 5
sudo partprobe /dev/${dev}

sudo mkfs.vfat /dev/$efi
sudo mke2fs -t ext2 -L tcore  -F /dev/$ext
#sudo mke2fs -t ext2 -L data  -F /dev/$work

is_tcl=$(cat /proc/cmdline | grep tce=)
if [ $? -eq 0 ]; then
   tce-load -i grub2-multi
else
   sudo mkdir -p /mnt/$efi
   sudo mkdir -p /mnt/$ext
   sudo mkdir -p /mnt/$work
   sudo apt-get -y install grub2
fi
sudo mount /dev/$efi /mnt/$efi
sudo mount /dev/$ext /mnt/$ext

if [ -n "$is_tce" ]; then
   sudo grub-install -s --target=x86_64-efi --boot-directory=/mnt/$efi/EFI/BOOT --efi-directory=/mnt/$efi --removable --directory=/usr/local/lib/grub/i386-efi/
   if [ $? -ne 0 ];then exit 1;fi
   sudo grub-install --target=i386-pc --boot-directory=/mnt/$efi/EFI/BOOT /dev/${dev}
else
   sudo grub-install  --target=x86_64-efi --boot-directory=/mnt/$efi/EFI/BOOT --efi-directory=/mnt/$efi --removable --directory=/usr/lib/grub/x86_64-efi/
   if [ $? -ne 0 ];then exit 1;fi
   sudo grub-install --target=i386-pc --force --boot-directory=/mnt/$efi/EFI/BOOT /dev/${dev}
fi
if [ $? -ne 0 ];then exit 1;fi

sudo mkdir -p /mnt/$ext/boot
sudo mkdir -p /mnt/$ext/tce/optional
sudo mkdir -p /mnt/$ext/opt/iiab
sudo mkdir -p /mnt/$ext/home

pushd /mnt/$ext/boot
sudo wget http://tinycorelinux.net/9.x/x86/release/distribution_files/vmlinuz
#sudo wget http://tinycorelinux.net/9.x/x86/release/distribution_files/vmlinuz64
sudo wget http://tinycorelinux.net/9.x/x86/release/distribution_files/rootfs.gz
sudo wget http://tinycorelinux.net/9.x/x86/release/distribution_files/modules.gz
#sudo wget http://tinycorelinux.net/9.x/x86/release/distribution_files/modules64.gz
popd

sudo cp iiab.lst /mnt/$ext/tce/
if [ -n is_tcl ]; then
   sudo cp /mnt/sdb2/tce/mydata.tgz /mnt/$ext/tce/mydata.tgz
   sudo cp -r /mnt/sdb2/opt /mnt/$ext/
fi
sudo cp -f load.sh /mnt/$ext/tce
if [ ! -d /mnt/$ext/opt/iiab/iiab-factory ]; then
   pushd /mnt/$ext/opt/iiab
      sudo git clone https://github.com/iiab/iiab-factory
      sync
      cd ./iiab-factory
      sudo git remote add ghunt https://github.com/georgejhunt/iiab-factory
      sudo git fetch --all
      sudo git checkout -b fixes ghunt/fixes
   popd
fi

PERSIST=/opt/cache/tce
sudo mkdir -p $PERSIST/optional
ARCH=x86
CORE_VERSION=9.x

sudo chmod 775 -R $PERSIST
    # download tiny core extension
sudo cat << EOF |sudo tee $PERSIST/onboot.lst
pci-utils.tcz
git.tcz
tree.tcz
bash.tcz
slocate.tcz
grub2-multi.tcz
dialog.tcz
dosfstools.tcz
util-linux.tcz
zip-unzip.tcz
ntfs-3g.tcz
coreutils.tcz
bc.tcz
flex.tcz
ncurses.tcz
ncurses-utils.tcz
nss-mdns.tcz
openssh.tcz
rsync.tcz
sed.tcz
tar.tcz
wget.tcz
e2fsprogs.tcz
ntfsprogs.tcz
hfsprogs.tcz
usbutils.tcz
grep.tcz
getlocale.tcz
setfont.tcz
mylocale.tcz
EOF
# note:  mylocale.tcz needs to be generated on TCL and copied to $PERSIST
# wait for the new file to be available
sudo sync
get_tce_file(){
    if [ ! -f $1 ]; then
        sudo wget ${flags} ${base}/${ARCH}/tcz/$1
        sudo wget ${flags} ${base}/${ARCH}/tcz/$1.md5.txt
        sudo wget ${flags} ${base}/${ARCH}/tcz/$1.dep
	for dep in `cat $1.dep`; do
 		get_tce_file $dep
	done
        p_end "got $file"
    else
        if [ $CACHE = no ]; then
            sudo rm -f $1.md5.txt
            sudo wget ${flags} ${base}/${ARCH}/tcz/$1.md5.txt  
            if [ "$(cat $1.md5.txt | cut -f 1 -d ' ')" \
                != "$(md5sum $1 | cut -f 1 -d ' ')" ]; then
                sudo rm -f $1{,.dep}
                sudo wget ${flags} ${base}/${ARCH}/tcz/$1
                sudo wget ${flags} ${base}/${ARCH}/tcz/$1.dep
                p_end "updated $1"
            fi
            for dep in `cat $1.dep`; do
               get_tce_file $dep
            done
        fi
    fi
}

p_begin "Checking Tiny Core extensions ... "
base=http://repo.tinycorelinux.net/${CORE_VERSION}
pushd $PERSIST/optional
flags="-q -c "

for file in $(<${PERSIST}/onboot.lst); do
   get_tce_file $file
done
popd > /dev/null
p_end "ok"

sudo partprobe /dev/${dev}
sleep 3
uuid=$(lsblk -o LABEL,UUID | grep tcore | awk '{print $2}')
echo $uuid
cat grub.cfg | sed -e "s/IIAB_TOKEN/$uuid/g" | sudo tee /mnt/$efi/EFI/BOOT/grub/grub.cfg
copy_package(){
   sudo rsync -a $PERSIST/optional/$1 /mnt/$ext/tce/optional/
   sudo rsync -a $PERSIST/optional/$1.dep /mnt/$ext/tce/optional/
   for dep in `cat $PERSIST/optional/$1.dep`; do
      copy_package $dep
   done
}
sudo mkdir -p /mnt/$ext/tce/optional
for file in $(<${PERSIST}/onboot.lst); do
   copy_package $file
done
sudo rsync $PERSIST/onboot.lst /mnt/$ext/tce/
sudo wget -P /mnt/$ext/tce/ $URL/mydata.tgz

sync


