#!/bin/bash 
# check/copy the files in the list to an output path

# soft code the output directory
prefix='/library'

# check for proper inputs
if [ $# -eq 0 ]; then
    echo "Required parameter is  filename of the <subset>.ini file."
    exit 1
fi
if [ ! -f $1 ]; then
    echo "$1 not found."
    exit 1
fi
subset=`grep subset_name $1 | gawk '{print $3;}'`

# see if the list is prepared
if [ ! -f $prefix/working/osm/$subset/$subset.list ];then
    echo "Please run mk_subset first"
    exit 1
fi

for f in `cat $prefix/working/osm/$subset/$subset.list`;do
   if [ ! -f $f ]; then
      echo $f not found
   else
      dest=`dirname $f`
      dest=`echo $dest|sed -E 's%.*default/(.*)%\1%'`
      mkdir -p $prefix/working/osm/$subset/output/$dest
      rsync -a $f $prefix/working/osm/$subset/output/$dest/
   fi
done
space=`du -sh $prefix/working/osm/$subset/output`
echo "du -sh reports: $space"
space=`echo $space|gawk '{print $1;}'`

# put the ini file where the script will find it after pushd
cp $1 $prefix/working/osm/$subset/

# now create a zip file which includes this subset
pushd $prefix/working/osm/$subset/output
zip -rp $subset.zip *

# create an information file about this subset
cat <<EOF > $subset.info
#!/bin/bash
#
# Generated by iiab-factory/content/subset-osm/mk-subset.py
#
# Total size of unzipped archive: $space
#
# Command to unzip files to their proper directories
#
unzip -d /library/knowledge/modules/openstreetmap/mod_tile64/default/ ./$subset.zip
EOF
echo -e "\n\n#The following values were used to define the bounding box for this subset\n" >> $subset.info
while read  line;do 
    echo "#$line" >> $subset.info
done < ../$1
echo -e "\n\n#Details of the subset generation process:.\n" >> $subset.info
while read  line;do 
    echo "#$line" >> $subset.info
done < ../$subset.info

# add the information file to the zipped up data
zip -g $subset.zip $subset.info

# add a shell script to autoinstall the osm tree
cp $subset.info autounzip.sh
chmod 755 autounzip.sh
zip -g $subset.zip autounzip.sh
rm autounzip.sh

popd
