#!/bin/bash

source ../find-source

CP_KA=../../khan/ka-vids

# automate download of content pack
export KALITE_HOME=/library/ka-lite
kalite manage retrievecontentpack download es

$CP_KA -l es -c $KA_SRC khan/math/early-math/
$CP_KA -l es -c $KA_SRC khan/math/arithmetic/
$CP_KA -l es -c $KA_SRC khan/math/pre-algebra/
$CP_KA -l es -c $KA_SRC khan/math/algebra-basics/
$CP_KA -l es -c $KA_SRC khan/math/algebra/
$CP_KA -l es -c $KA_SRC khan/math/basic-geo/
$CP_KA -l es -c $KA_SRC khan/math/geometry/
$CP_KA -l es -c $KA_SRC khan/math/algebra2/
$CP_KA -l es -c $KA_SRC khan/math/trigonometry/
$CP_KA -l es -c $KA_SRC khan/science/
$CP_KA -l es -c $KA_SRC khan/economics-finance-domain/
$CP_KA -l es -c $KA_SRC khan/computing/

# automate directory scan
export KALITE_HOME=/library/ka-lite
kalite manage videoscan --language=es
