#!/bin/bash

if [ -z "$MOD_SRC" ]; then
  echo 'export MOD_SRC=<full path to modules directory from which to copy'
  exit 1
fi

CP_MOD=../../modules/cp-mod

$CP_MOD es-ap_didact
$CP_MOD es-bibliofilo
$CP_MOD es-biblioteca
$CP_MOD es-ebooks
$CP_MOD es-educalab
$CP_MOD es-hesperian_health
$CP_MOD es-medline_plus
$CP_MOD es-soluciones
$CP_MOD es-blockly_games
$CP_MOD es-vedoque
$CP_MOD phet-html
