#!/bin/bash
# copy action routines to where they reside

cp -f ./viewer.php /library/www/html/info/videos/viewer.php
cp -f  ./viewer.js /library/www/html/info/videos/viewer.js
cp -f  ./viewer.css /library/www/html/info/videos/viewer.css
cp -f  ./cc_list.php /library/www/html/info/videos/
cp -f  ./metadata.php /library/www/html/info/videos/
cp -f  ./metadata.php /opt/admin/console/
cp -f  ./index.php /library/www/html/info/videos/
cp -f  ./js-menu.js /library/www/html/info/videos/
